name: Laravel CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [8.3]
        
    name: PHP ${{ matrix.php-version }} Test
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, dom, fileinfo, mysql, sqlite3, pdo_sqlite, bcmath, gd, exif, iconv, imagick, zip
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: |
        chmod -R 777 storage bootstrap/cache
        mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views
        chmod -R 777 storage

    - name: Create Database Directory
      run: mkdir -p database

    - name: Create Testing Database
      run: touch database/testing.sqlite

    - name: Set Testing Environment
      run: |
        # Get APP_KEY from main .env file
        APP_KEY=$(grep "^APP_KEY=" .env | cut -d '=' -f2-)
        
        # Create clean .env.testing
        echo "APP_NAME=Laravel" > .env.testing
        echo "APP_ENV=testing" >> .env.testing
        echo "APP_KEY=$APP_KEY" >> .env.testing
        echo "APP_DEBUG=true" >> .env.testing
        echo "APP_URL=http://localhost:8000" >> .env.testing
        echo "DB_CONNECTION=sqlite" >> .env.testing  
        echo "DB_DATABASE=/home/runner/work/laravel_building_2025/laravel_building_2025/database/testing.sqlite" >> .env.testing
        echo "CACHE_DRIVER=array" >> .env.testing
        echo "QUEUE_CONNECTION=sync" >> .env.testing
        echo "SESSION_DRIVER=array" >> .env.testing
        echo "MAIL_MAILER=array" >> .env.testing
        echo "TELESCOPE_ENABLED=false" >> .env.testing
        echo "PERMISSION_VALIDATION_ENABLED=true" >> .env.testing
        echo "LOG_CHANNEL=stack" >> .env.testing
        echo "LOG_LEVEL=debug" >> .env.testing

    - name: Clear Config Cache
      run: |
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan cache:clear
        php artisan config:cache --env=testing

    - name: Run Database Migrations
      run: php artisan migrate --env=testing --force

    - name: Seed Database
      run: php artisan db:seed --env=testing --force

    - name: Debug Environment
      run: |
        echo "=== Environment Check ==="
        php artisan --version
        echo "=== .env.testing Content ==="
        cat .env.testing
        echo "=== Database Check ==="
        ls -la database/
        echo "=== Storage Permissions ==="
        ls -la storage/
        echo "=== Test Database Connection ==="
        php artisan migrate:status --env=testing || echo "Migration status failed"

    - name: Start Laravel Server (Background)
      run: php artisan serve --port=8000 --env=testing &
      env:
        APP_ENV: testing

    - name: Wait for Server
      run: |
        echo "Waiting for Laravel server to start..."
        sleep 5
        echo "Testing server response..."
        for i in {1..10}; do
          echo "Attempt $i/10..."
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep -q "200\|302"; then
            echo "✅ Server is responding!"
            break
          fi
          if [ $i -eq 10 ]; then
            echo "❌ Server failed to respond after 10 attempts"
            echo "=== Server Logs ==="
            tail -20 storage/logs/laravel.log || echo "No Laravel log found"
            exit 1
          fi
          sleep 3
        done

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test --env=testing

    - name: Execute standalone permission test
      run: php tests/01-test-permission-standalone.php
      continue-on-error: true

    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Laravel Logs ==="
        tail -50 storage/logs/laravel.log || echo "No Laravel log found"
        echo "=== Server Status ==="
        curl -I http://localhost:8000 || echo "Server not responding"