name: Laravel CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: [8.3]
        
    name: PHP ${{ matrix.php-version }} Test
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, dom, fileinfo, mysql, sqlite3, pdo_sqlite, bcmath, gd, exif, iconv, imagick, zip
        coverage: none

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: |
        chmod -R 777 storage bootstrap/cache
        mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views
        chmod -R 777 storage

    - name: Create Database Directory
      run: mkdir -p database

    - name: Create Testing Database
      run: touch database/testing.sqlite

    - name: Set Testing Environment
      run: |
        # Update .env.testing for CI environment only
        sed -i 's|APP_URL=.*|APP_URL=http://localhost:12368|' .env.testing
        sed -i 's|DB_DATABASE=.*|DB_DATABASE=/home/runner/work/laravel_building_2025/laravel_building_2025/database/testing.sqlite|' .env.testing

    - name: Clear Config Cache
      run: |
        php artisan config:clear
        php artisan route:clear
        php artisan view:clear
        php artisan cache:clear
        php artisan config:cache --env=testing

    - name: Run Database Migrations
      run: php artisan migrate --env=testing --force

    - name: Seed Database
      run: php artisan db:seed --env=testing --force

    - name: Debug Environment
      run: |
        echo "=== Environment Check ==="
        php artisan --version
        echo "=== .env.testing Content ==="
        cat .env.testing
        echo "=== Database Check ==="
        ls -la database/
        echo "=== Storage Permissions ==="
        ls -la storage/
        echo "=== Test Database Connection ==="
        php artisan migrate:status --env=testing || echo "Migration status failed"



    - name: Discover Standalone Test Files
      id: discover-tests
      run: |
        # Find all test files matching pattern: {number}-*.php
        test_files=$(find tests/ -name '[0-9]*-*.php' -type f | sort -V)
        echo "Found test files:"
        echo "$test_files"
        
        # Convert to JSON array for matrix strategy
        test_matrix=$(echo "$test_files" | jq -R -s -c 'split("\n")[:-1]')
        echo "test-files=$test_matrix" >> $GITHUB_OUTPUT

    - name: Execute All Standalone Tests (Include Mode)
      run: php tests/run_all_test.php --env=testing

    - name: Show logs on failure
      if: failure()
      run: |
        echo "=== Laravel Logs ==="
        tail -50 storage/logs/laravel.log || echo "No Laravel log found"
        echo "=== Server Status ==="
        curl -I http://localhost:12368 || echo "Server not responding"
        echo "=== Running Processes ==="
        ps aux | grep -E "(php|artisan)" || echo "No PHP processes found"